<?php

/**
 * @file
 * Drupal.org user's statistics comparing module.
 */

/**
 * Implements hook_menu().
 */
function pp_comparing_menu() {
  $items = array();

  $items['comparing/%/data.tsv'] = array(
    'title' => 'Compare users stats',
    'page callback' => 'pp_comparing_users',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function pp_comparing_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Page callback for tsv for d3 lib.
 *
 * @param string $users
 *   User node nids separated by comma.
 */
function pp_comparing_users($users) {
  $types = $dates = array();
  if (!empty($_GET['types'])) {
    $types = explode(',', $_GET['types']);
  }

  if (!empty($_GET['from'])) {
    $dates['from'] = $_GET['from'];
  }

  if (!empty($_GET['till'])) {
    $dates['till'] = $_GET['till'];
  }

  $titles = array();
  $users = explode(',', $users);
  $data = _pp_comparing_users_data($users, $types, $dates);

  drupal_add_http_header('Cache-Control', 'private, max-age=' . 60 * 60 * 24);
  drupal_add_http_header('Content-Type', 'application/octet-stream');
  drupal_add_http_header('Content-Transfer-Encoding', 'binary');

  foreach (node_load_multiple($users) as $user_node) {
    $titles[] = $user_node->title;
  }

  print 'date	' . implode('	', $titles) . "\n";

  if (is_string($data)) {
    return;
  }

  foreach ($data as $value) {
    $date = $value['timestamp'];
    unset($value['timestamp']);
    print str_replace(' ', '-', $date) . '	' . implode('	', $value) . "\n";
  }

  drupal_exit();
}

/**
 * Get structured map of users stats by granular timestamp.
 *
 * @param array $users
 *   List of user nodes nid.
 * @param array $types
 *   List of stats type.
 *
 * @return array
 *   Array of statistics per week.
 */
function _pp_comparing_users_data($users, $types, $dates) {
  $table_data = array();
  $users = node_load_multiple($users);

  foreach ($users as $user_node) {
    if (empty($user_node->field_user_id[LANGUAGE_NONE][0]['value'])) {
      watchdog('warning', 'User ' . $user_node->title . ' doesn\'t have attached d.rog UID!');
      continue;
    }

    $doid = $user_node->field_user_id[LANGUAGE_NONE][0]['value'];

    $query = db_select('ppgetstat', 'ppst')
      ->fields('ppst', array('timestamp', 'items'))
      ->condition('ppst.doid', $doid)
      ->groupBy('timestamp')
      ->orderBy('ppst.timestamp', 'DESC');

    $query->addExpression('SUM(items)', 'commits_count');

    if (!empty($dates['from'])) {
      $query->condition('ppst.timestamp', $dates['from'], '>=');
    }

    if (!empty($dates['till'])) {
      $query->condition('ppst.timestamp', $dates['till'], '<=');
    }

    if (!empty($types)) {
      $query->condition('ppst.type', $types, 'IN');
    }

    $db_data = $query->execute()->fetchAllAssoc('timestamp');

    $beginning = (!empty($dates['from'])) ? $dates['from'] : REQUEST_TIME - PPGETSTAT_DEFAULT_TIME_PERIOD_FOR_SCANNING;
    $timestamp = $beginning - ($beginning % PPGETSTAT_TIME_WEEK_GRANULARITY);

    $till_time = !empty($dates['till']) ? $dates['till'] : REQUEST_TIME;
    while ($timestamp < $till_time) {
      $commits = 0;
      if (isset($db_data[$timestamp])) {
        $commits = $db_data[$timestamp]->commits_count;
      }
      $table_data[$timestamp]['timestamp'] = format_date($timestamp, 'custom', 'j M y');
      $table_data[$timestamp][$doid] = $commits;

      $timestamp += PPGETSTAT_TIME_WEEK_GRANULARITY;
    }

  }

  return $table_data;
}
